# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ivan Pavlak
title: Robotics Engineer
email: ivan.pavlak3@gmail.com
website: ipavlak.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username: IPavlak
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: ivan-pavlak-3838571aa
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I graduated from Faculty of Electrical Engineering and Computing, **University of Zagreb** in 2021. Primary focus of my education was control systems design and robotics in general.
  For my Master's thesis I implemented path generation for UAVs that are visually inspecting buildings.

  In 2021. after my graduation, I started working at Croatian based startup **Gideon Brothers**. My primary focus there was **navigation**, more precisely path following algorithms. But I had a chance to work on a lot of different aspects of robotics, I worked on control system for steering on double ackermann drive, path generation, detection of moving obstacles, communication between robots and coordination of multiple robots with time optimization.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UAV path generation - building inspections
        link: github.com/IPavlak/GmapsGMLDrawing
        # link_text: Project Website
        additional_links:
          - title:  GmapsGMLDrawing
            icon: fab fa-github
            url: github.com/IPavlak/GmapsGMLDrawing
        #quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Project was developed for my Master's thesis. It was consisted of 2 parts: path generation algorithm and desktop app for parameter input and path visualization.
          App gathered building data from online database, connected to Google maps to visualize that building and draw a generated path on it so operator can easily inspect the generated path in 2D space.

          &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; <img src="images/path_gen_thesis.png" width="350" height="auto">
            
          <br>
          <br> 
          <br>
          <br>  
            
            
      - layout: left
        title: Time series simulator
        link: github.com/IPavlak/time_series_simulator
        additional_links:
          - title: Time Series Simulator
            icon: fab fa-github
            url: https://github.com/IPavlak/time_series_simulator
        description: |
          This was my personal project. I wanted to test some of my machine learning algorithms on real market data, unfortunately I did not find any simulator on which I could run Python code.
          So as a personal project and opportunity to learn different frameworks like pandas library or Qt, I started working on my own timeseries simulator.

          <br>

          &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; <img src="images/time_series_sim.png" width="350" height="auto">


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: right
        title: Gideon Brothers
        link: gideon.ai
        # link_text: gideonbros.ai
        sub_title: Navigation engineer
        caption: 2021 - Present
        quote: >
          Building the world's most flexible autonomous mobile robots
        description: |   # this will include new lines to allow paragraphs    # TODO: table -> description | 
          My primary job was designing and developing **path following algorithm**, it sends velocity references to robot in order to follow given path. I was in charge of creating and implementing code architecture for that part of the stack. During my time at the company I also had a chance to work on many other fields and gain experience in different parts of stack, from low level control system to high level multirobot operations.

          Some of the projects I was involved in are
            * designing PID regulator for robot turning
            * develop detection and tracking of moving obstacles based on recent papers using 2D lidars
            * develop communication system between multiple robots
            * develop multirobot coordination algorithm with time optimizations.

          <br>
          <br>

      - layout: left
        title: FER
        link: fer.unizg.hr
        # link_text: fer.unizg.hr
        sub_title: Junior C++ developer
        caption: 2020 - 2021 Part time
        quote: >
          Leading national and regional high education institution
        description: | # this will include new lines to allow paragraphs
         Designing a trajectory suitable for inspection of buildings and wind turbines. Using C++ PCL library to process point clouds and obtain desired trajectory.

          <br>
          <br>

      - layout: right
        title: Geolux
        link: geolux-radars.com
        # link_text: geolux-radars.com
        sub_title: Machine learning programmer
        caption: Sep 2019 - Oct 2019 Internship
        quote: >
          We are a European-based fast-growing company and niche leader in the hydrology radar and sensor industry
        description: | # this will include new lines to allow paragraphs
          Design **convolutional neural** network suited for their specific problem and implementing network in Python. After successful training and testing, implementing that network in C++ for prediction (forward pass only).

          <br>
          <br>

      - layout: left
        title: Ericsson
        link: ericsson.com
        # link_text: ericsson.com
        sub_title: MATLAB programmer
        caption: Jul 2019 - Sep 2019 Internship
        quote: >
          We create connections that make the unimaginable possible
        description: | # this will include new lines to allow paragraphs
          I worked in a team that was designing a model of **OFDM communication system** in MATLAB. We had to design the whole system from scratch and later implement that model on real RF platform. Assignment was completed successfully.

          <br>
          <br>

      - layout: right
        title: FER
        link: fer.unizg.hr
        # link_text: fer.unizg.hr
        sub_title: Teacher assistant - electromagnetic fields
        caption: Feb 2017 - Jun 2017
        quote: >
          Leading national and regional high education institution
        description: | # this will include new lines to allow paragraphs
          Helping students with their tasks on practical exercises.



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Zagreb
        caption: 2018 - 2021
        sub_title: MSc Automation
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading #         #university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Thesis: <i> ... generating path ... </i>

      - layout: left
        title: University of Zagreb
        caption: 2015 - 2018
        sub_title: BSc Automation
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading #         #university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Thesis: <i> ... acrobatic manuevers </i>

  - title: Skillset
    layout: text
    content: | # this will include new lines to allow paragraphs
      During my career I have gained experience in many different fields I had interest in. My goal was to have basic understanding of how things work, on higher at least. So for example I have basic understanding of machine (and deep) learning and I worked with convolutinal networks. Also I have some experience in designing some signal filters and control systems (regulators).
Great most of my work was on Linux, so I have some intermediate knowledge of the system.

      <mark>C++ &emsp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;&emsp; </mark>

      <mark>Python &emsp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;&emsp; </mark>

      <mark>ROS &emsp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;&emsp; </mark>

      <mark>Docker &emsp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;&emsp; &emsp;%emsp; </mark>

      <mark>MATLAB &emsp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;&emsp;</mark>

      <mark>Control systems &emsp;&emsp;&emsp; </mark>

      <mark>ML &emsp;&emsp;&emsp;&emsp; &emsp; </mark>

      <mark>Java/C# &emsp;&emsp;&emsp;&emsp; &emsp; </mark>

      <mark>Git &emsp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp; </mark>


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
